// <auto-generated />
using EFFilm_1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFFilm_1.Migrations
{
    [DbContext(typeof(MovieDBContext))]
    partial class MovieDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFFilm_1.Entites.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActeurPrincipal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AnneeDeSortie")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Realisateur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Titre")
                        .IsUnique();

                    b.ToTable("Movie", null, t =>
                        {
                            t.HasCheckConstraint("CK_Annee", "AnneeDeSortie>1975");
                        });

                    b.HasData(
                        new
                        {
                            Id = 2,
                            ActeurPrincipal = "Robert De Niro",
                            AnneeDeSortie = 1976,
                            Genre = "Drame",
                            Realisateur = "Martin Scorsese",
                            Titre = "Taxi Driver"
                        },
                        new
                        {
                            Id = 3,
                            ActeurPrincipal = "Mark Hamill",
                            AnneeDeSortie = 1977,
                            Genre = "Science-Fiction",
                            Realisateur = "George Lucas",
                            Titre = "Star Wars: Episode IV"
                        },
                        new
                        {
                            Id = 4,
                            ActeurPrincipal = "Martin Sheen",
                            AnneeDeSortie = 1979,
                            Genre = "Guerre",
                            Realisateur = "Francis Ford Coppola",
                            Titre = "Apocalypse Now"
                        },
                        new
                        {
                            Id = 5,
                            ActeurPrincipal = "Sigourney Weaver",
                            AnneeDeSortie = 1979,
                            Genre = "Science-Fiction/Horreur",
                            Realisateur = "Ridley Scott",
                            Titre = "Alien"
                        },
                        new
                        {
                            Id = 6,
                            ActeurPrincipal = "Jack Nicholson",
                            AnneeDeSortie = 1980,
                            Genre = "Horreur",
                            Realisateur = "Stanley Kubrick",
                            Titre = "The Shining"
                        },
                        new
                        {
                            Id = 7,
                            ActeurPrincipal = "Harrison Ford",
                            AnneeDeSortie = 1981,
                            Genre = "Aventure",
                            Realisateur = "Steven Spielberg",
                            Titre = "Raiders of the Lost Ark"
                        },
                        new
                        {
                            Id = 8,
                            ActeurPrincipal = "Henry Thomas",
                            AnneeDeSortie = 1982,
                            Genre = "Science-Fiction",
                            Realisateur = "Steven Spielberg",
                            Titre = "E.T."
                        },
                        new
                        {
                            Id = 9,
                            ActeurPrincipal = "Harrison Ford",
                            AnneeDeSortie = 1982,
                            Genre = "Science-Fiction",
                            Realisateur = "Ridley Scott",
                            Titre = "Blade Runner"
                        },
                        new
                        {
                            Id = 10,
                            ActeurPrincipal = "Al Pacino",
                            AnneeDeSortie = 1983,
                            Genre = "Crime",
                            Realisateur = "Brian De Palma",
                            Titre = "Scarface"
                        },
                        new
                        {
                            Id = 11,
                            ActeurPrincipal = "Arnold Schwarzenegger",
                            AnneeDeSortie = 1984,
                            Genre = "Science-Fiction",
                            Realisateur = "James Cameron",
                            Titre = "Terminator"
                        },
                        new
                        {
                            Id = 12,
                            ActeurPrincipal = "Michael J. Fox",
                            AnneeDeSortie = 1985,
                            Genre = "Science-Fiction",
                            Realisateur = "Robert Zemeckis",
                            Titre = "Retour vers le futur"
                        },
                        new
                        {
                            Id = 13,
                            ActeurPrincipal = "Sigourney Weaver",
                            AnneeDeSortie = 1986,
                            Genre = "Science-Fiction/Action",
                            Realisateur = "James Cameron",
                            Titre = "Aliens"
                        },
                        new
                        {
                            Id = 14,
                            ActeurPrincipal = "Matthew Modine",
                            AnneeDeSortie = 1987,
                            Genre = "Guerre",
                            Realisateur = "Stanley Kubrick",
                            Titre = "Full Metal Jacket"
                        },
                        new
                        {
                            Id = 15,
                            ActeurPrincipal = "Bruce Willis",
                            AnneeDeSortie = 1988,
                            Genre = "Action",
                            Realisateur = "John McTiernan",
                            Titre = "Die Hard"
                        },
                        new
                        {
                            Id = 16,
                            ActeurPrincipal = "Michael Keaton",
                            AnneeDeSortie = 1989,
                            Genre = "Action",
                            Realisateur = "Tim Burton",
                            Titre = "Batman"
                        },
                        new
                        {
                            Id = 17,
                            ActeurPrincipal = "Ray Liotta",
                            AnneeDeSortie = 1990,
                            Genre = "Crime",
                            Realisateur = "Martin Scorsese",
                            Titre = "Les Affranchis"
                        },
                        new
                        {
                            Id = 18,
                            ActeurPrincipal = "Jodie Foster",
                            AnneeDeSortie = 1991,
                            Genre = "Thriller",
                            Realisateur = "Jonathan Demme",
                            Titre = "Le Silence des agneaux"
                        },
                        new
                        {
                            Id = 19,
                            ActeurPrincipal = "Harvey Keitel",
                            AnneeDeSortie = 1992,
                            Genre = "Crime",
                            Realisateur = "Quentin Tarantino",
                            Titre = "Reservoir Dogs"
                        },
                        new
                        {
                            Id = 20,
                            ActeurPrincipal = "Sam Neill",
                            AnneeDeSortie = 1993,
                            Genre = "Aventure",
                            Realisateur = "Steven Spielberg",
                            Titre = "Jurassic Park"
                        },
                        new
                        {
                            Id = 21,
                            ActeurPrincipal = "John Travolta",
                            AnneeDeSortie = 1994,
                            Genre = "Crime",
                            Realisateur = "Quentin Tarantino",
                            Titre = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 22,
                            ActeurPrincipal = "Brad Pitt",
                            AnneeDeSortie = 1995,
                            Genre = "Thriller",
                            Realisateur = "David Fincher",
                            Titre = "Seven"
                        },
                        new
                        {
                            Id = 23,
                            ActeurPrincipal = "Frances McDormand",
                            AnneeDeSortie = 1996,
                            Genre = "Crime",
                            Realisateur = "Joel Coen",
                            Titre = "Fargo"
                        },
                        new
                        {
                            Id = 24,
                            ActeurPrincipal = "Leonardo DiCaprio",
                            AnneeDeSortie = 1997,
                            Genre = "Drame/Romance",
                            Realisateur = "James Cameron",
                            Titre = "Titanic"
                        },
                        new
                        {
                            Id = 25,
                            ActeurPrincipal = "Tom Hanks",
                            AnneeDeSortie = 1998,
                            Genre = "Guerre",
                            Realisateur = "Steven Spielberg",
                            Titre = "Il faut sauver le soldat Ryan"
                        },
                        new
                        {
                            Id = 26,
                            ActeurPrincipal = "Keanu Reeves",
                            AnneeDeSortie = 1999,
                            Genre = "Science-Fiction",
                            Realisateur = "Lana et Lilly Wachowski",
                            Titre = "Matrix"
                        },
                        new
                        {
                            Id = 27,
                            ActeurPrincipal = "Guy Pearce",
                            AnneeDeSortie = 2000,
                            Genre = "Thriller",
                            Realisateur = "Christopher Nolan",
                            Titre = "Memento"
                        },
                        new
                        {
                            Id = 28,
                            ActeurPrincipal = "Elijah Wood",
                            AnneeDeSortie = 2001,
                            Genre = "Fantasy",
                            Realisateur = "Peter Jackson",
                            Titre = "Le Seigneur des anneaux"
                        },
                        new
                        {
                            Id = 29,
                            ActeurPrincipal = "Alexandre Rodrigues",
                            AnneeDeSortie = 2002,
                            Genre = "Crime",
                            Realisateur = "Fernando Meirelles",
                            Titre = "City of God"
                        },
                        new
                        {
                            Id = 30,
                            ActeurPrincipal = "Uma Thurman",
                            AnneeDeSortie = 2003,
                            Genre = "Action",
                            Realisateur = "Quentin Tarantino",
                            Titre = "Kill Bill: Vol. 1"
                        },
                        new
                        {
                            Id = 31,
                            ActeurPrincipal = "Jim Carrey",
                            AnneeDeSortie = 2004,
                            Genre = "Drame/Romance",
                            Realisateur = "Michel Gondry",
                            Titre = "Eternal Sunshine"
                        },
                        new
                        {
                            Id = 32,
                            ActeurPrincipal = "Christian Bale",
                            AnneeDeSortie = 2005,
                            Genre = "Action",
                            Realisateur = "Christopher Nolan",
                            Titre = "Batman Begins"
                        },
                        new
                        {
                            Id = 33,
                            ActeurPrincipal = "Leonardo DiCaprio",
                            AnneeDeSortie = 2006,
                            Genre = "Crime",
                            Realisateur = "Martin Scorsese",
                            Titre = "Les Infiltrés"
                        },
                        new
                        {
                            Id = 34,
                            ActeurPrincipal = "Josh Brolin",
                            AnneeDeSortie = 2007,
                            Genre = "Crime",
                            Realisateur = "Joel et Ethan Coen",
                            Titre = "No Country for Old Men"
                        },
                        new
                        {
                            Id = 35,
                            ActeurPrincipal = "Christian Bale",
                            AnneeDeSortie = 2008,
                            Genre = "Action",
                            Realisateur = "Christopher Nolan",
                            Titre = "The Dark Knight"
                        },
                        new
                        {
                            Id = 36,
                            ActeurPrincipal = "Sam Worthington",
                            AnneeDeSortie = 2009,
                            Genre = "Science-Fiction",
                            Realisateur = "James Cameron",
                            Titre = "Avatar"
                        },
                        new
                        {
                            Id = 37,
                            ActeurPrincipal = "Leonardo DiCaprio",
                            AnneeDeSortie = 2010,
                            Genre = "Science-Fiction",
                            Realisateur = "Christopher Nolan",
                            Titre = "Inception"
                        },
                        new
                        {
                            Id = 38,
                            ActeurPrincipal = "Ryan Gosling",
                            AnneeDeSortie = 2011,
                            Genre = "Crime",
                            Realisateur = "Nicolas Winding Refn",
                            Titre = "Drive"
                        },
                        new
                        {
                            Id = 39,
                            ActeurPrincipal = "Jamie Foxx",
                            AnneeDeSortie = 2012,
                            Genre = "Western",
                            Realisateur = "Quentin Tarantino",
                            Titre = "Django Unchained"
                        },
                        new
                        {
                            Id = 40,
                            ActeurPrincipal = "Sandra Bullock",
                            AnneeDeSortie = 2013,
                            Genre = "Science-Fiction",
                            Realisateur = "Alfonso Cuarón",
                            Titre = "Gravity"
                        },
                        new
                        {
                            Id = 41,
                            ActeurPrincipal = "Matthew McConaughey",
                            AnneeDeSortie = 2014,
                            Genre = "Science-Fiction",
                            Realisateur = "Christopher Nolan",
                            Titre = "Interstellar"
                        },
                        new
                        {
                            Id = 42,
                            ActeurPrincipal = "Tom Hardy",
                            AnneeDeSortie = 2015,
                            Genre = "Action",
                            Realisateur = "George Miller",
                            Titre = "Mad Max: Fury Road"
                        },
                        new
                        {
                            Id = 43,
                            ActeurPrincipal = "Ryan Gosling",
                            AnneeDeSortie = 2016,
                            Genre = "Musical",
                            Realisateur = "Damien Chazelle",
                            Titre = "La La Land"
                        },
                        new
                        {
                            Id = 44,
                            ActeurPrincipal = "Daniel Kaluuya",
                            AnneeDeSortie = 2017,
                            Genre = "Horreur",
                            Realisateur = "Jordan Peele",
                            Titre = "Get Out"
                        },
                        new
                        {
                            Id = 45,
                            ActeurPrincipal = "Yalitza Aparicio",
                            AnneeDeSortie = 2018,
                            Genre = "Drame",
                            Realisateur = "Alfonso Cuarón",
                            Titre = "Roma"
                        },
                        new
                        {
                            Id = 46,
                            ActeurPrincipal = "Song Kang-ho",
                            AnneeDeSortie = 2019,
                            Genre = "Drame",
                            Realisateur = "Bong Joon-ho",
                            Titre = "Parasite"
                        },
                        new
                        {
                            Id = 47,
                            ActeurPrincipal = "Sylvester Stallone",
                            AnneeDeSortie = 1976,
                            Genre = "Drame",
                            Realisateur = "John G. Avildsen",
                            Titre = "Rocky"
                        },
                        new
                        {
                            Id = 48,
                            ActeurPrincipal = "Tim Robbins",
                            AnneeDeSortie = 1994,
                            Genre = "Drame",
                            Realisateur = "Frank Darabont",
                            Titre = "Les Évadés"
                        },
                        new
                        {
                            Id = 49,
                            ActeurPrincipal = "Brad Pitt",
                            AnneeDeSortie = 1999,
                            Genre = "Drame",
                            Realisateur = "David Fincher",
                            Titre = "Fight Club"
                        },
                        new
                        {
                            Id = 50,
                            ActeurPrincipal = "Russell Crowe",
                            AnneeDeSortie = 2000,
                            Genre = "Action",
                            Realisateur = "Ridley Scott",
                            Titre = "Gladiator"
                        },
                        new
                        {
                            Id = 51,
                            ActeurPrincipal = "Al Pacino",
                            AnneeDeSortie = 1976,
                            Genre = "Crime",
                            Realisateur = "Francis Ford Coppola",
                            Titre = "Le Parrain"
                        },
                        new
                        {
                            Id = 52,
                            ActeurPrincipal = "Tom Hanks",
                            AnneeDeSortie = 1994,
                            Genre = "Drame",
                            Realisateur = "Robert Zemeckis",
                            Titre = "Forrest Gump"
                        },
                        new
                        {
                            Id = 53,
                            ActeurPrincipal = "Keanu Reeves",
                            AnneeDeSortie = 2003,
                            Genre = "Science-Fiction",
                            Realisateur = "Lana et Lilly Wachowski",
                            Titre = "Matrix Reloaded"
                        },
                        new
                        {
                            Id = 54,
                            ActeurPrincipal = "Gerard Butler",
                            AnneeDeSortie = 2006,
                            Genre = "Action",
                            Realisateur = "Zack Snyder",
                            Titre = "300"
                        },
                        new
                        {
                            Id = 55,
                            ActeurPrincipal = "Christian Bale",
                            AnneeDeSortie = 2006,
                            Genre = "Drame",
                            Realisateur = "Christopher Nolan",
                            Titre = "Le Prestige"
                        },
                        new
                        {
                            Id = 56,
                            ActeurPrincipal = "Clint Eastwood",
                            AnneeDeSortie = 2008,
                            Genre = "Drame",
                            Realisateur = "Clint Eastwood",
                            Titre = "Gran Torino"
                        },
                        new
                        {
                            Id = 57,
                            ActeurPrincipal = "Sharlto Copley",
                            AnneeDeSortie = 2009,
                            Genre = "Science-Fiction",
                            Realisateur = "Neill Blomkamp",
                            Titre = "District 9"
                        },
                        new
                        {
                            Id = 58,
                            ActeurPrincipal = "Jesse Eisenberg",
                            AnneeDeSortie = 2010,
                            Genre = "Drame",
                            Realisateur = "David Fincher",
                            Titre = "The Social Network"
                        },
                        new
                        {
                            Id = 59,
                            ActeurPrincipal = "Leonardo DiCaprio",
                            AnneeDeSortie = 2013,
                            Genre = "Drame",
                            Realisateur = "Martin Scorsese",
                            Titre = "Le Loup de Wall Street"
                        },
                        new
                        {
                            Id = 60,
                            ActeurPrincipal = "Miles Teller",
                            AnneeDeSortie = 2014,
                            Genre = "Drame",
                            Realisateur = "Damien Chazelle",
                            Titre = "Whiplash"
                        },
                        new
                        {
                            Id = 61,
                            ActeurPrincipal = "Michael Keaton",
                            AnneeDeSortie = 2015,
                            Genre = "Drame",
                            Realisateur = "Tom McCarthy",
                            Titre = "Spotlight"
                        },
                        new
                        {
                            Id = 62,
                            ActeurPrincipal = "Amy Adams",
                            AnneeDeSortie = 2016,
                            Genre = "Science-Fiction",
                            Realisateur = "Denis Villeneuve",
                            Titre = "Premier Contact"
                        },
                        new
                        {
                            Id = 63,
                            ActeurPrincipal = "Frances McDormand",
                            AnneeDeSortie = 2017,
                            Genre = "Drame",
                            Realisateur = "Martin McDonagh",
                            Titre = "Three Billboards"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
